
seed: 43
defaults:
  - model: default
  - acq_opt: highdim
  - acq: qlognei
  - benchmark: levy4_25

evol_state_maintainer: dummy
q: 1
init: sqrt
init_factor: 3
experiment_group: test
experiment_name: ${evol_state_maintainer}-${benchmark.name}_${acq.name}_run${seed}
result_path: results/${experiment_group}/${benchmark.name}/${acq.name}
include_in_path: ""
