name: eggholder2_25
benchmark: eggholder2_25
num_iters: 200
num_init: 20
parameters: null
bounds: [[-512, 512], [-512, 512], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1]]
noise_std: 0.01